parameters:
#    siposs_static.example.class: Siposs\StaticBundle\Example

services:
#    siposs_static.example:
#        class: %siposs_static.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
